FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

RUN chmod +x gradlew
RUN ./gradlew dependencies --no-daemon

COPY src src
RUN ./gradlew clean build -x test --no-daemon

EXPOSE 8080

ENV JAVA_OPTS="-XX:InitialRAMPercentage=70.0 \
           -XX:MaxRAMPercentage=70.0 \
           -XX:MetaspaceSize=128M \
           -XX:MaxMetaspaceSize=256M \
           -XX:+UseG1GC \
           -XX:+UseContainerSupport"

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS:-} -Dspring.profiles.active=${SPRING_ACTIVE_PROFILE:-local} -jar /app/build/libs/*.jar"]
