version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql
    command: --event-scheduler=ON
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-tier

  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    ports:
      - "8978:8978"
    volumes:
      - ./volumes/dbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - db
    restart: always

networks:
  app-tier:
    driver: bridge
